import { collection, getDocs, writeBatch, doc } from 'firebase/firestore';
import { db } from './firebase';
import { Product, Coupon } from './types';

// Compact representation to build 50+ beautiful fashion items
interface RawProduct {
  id: string;
  name: string;
  category: string;
  subCategory: string;
  price: number;
  offerPrice: number;
  images: string[];
  sizes: string[];
  colors: string[];
  ratings: number;
  reviewCount: number;
  description: string;
  material: string;
  fit: string;
  fabric: string;
  occasion: string;
  sleeve?: string;
  neckline?: string;
  stock: number;
  isTrending?: boolean;
  isBestSeller?: boolean;
  isNewArrival?: boolean;
  isTodayDeal?: boolean;
  isSummerCollection?: boolean;
  isFormalWear?: boolean;
  isCasualWear?: boolean;
  isFestivalCollection?: boolean;
}

const RAW_PRODUCTS_DATA: RawProduct[] = [
  // --- SHIRTS (15 Products) ---
  {
    id: 'prod_beige_striped_shirt',
    name: 'Striped Casual Premium Shirt',
    category: 'Shirts',
    subCategory: 'Striped Shirts',
    price: 799,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Beige Striped', 'Off-White'],
    ratings: 4.0,
    reviewCount: 42,
    description: 'Crisp, lightweight cotton striped shirt. Features custom vertical styling, premium button closures, and a regular casual fit. Perfect for hot summer days and semi-formal outings.',
    material: '100% Premium Cotton',
    fit: 'Regular Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Spread Collar',
    fabric: 'Fine Twill Striped',
    occasion: 'Casual Wear, Summer Outings',
    stock: 25,
    isTrending: true,
    isNewArrival: true,
    isSummerCollection: true,
    isCasualWear: true
  },
  {
    id: 'prod_olive_striped_shirt',
    name: 'Satin Elegance Striped Shirt',
    category: 'Shirts',
    subCategory: 'Striped Shirts',
    price: 799,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800&auto=format&fit=crop&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Olive Striped', 'Forest Green'],
    ratings: 4.0,
    reviewCount: 35,
    description: 'Smooth satin-finish cotton striped shirt. Gives a premium rich look with comfortable breathable weave. Designed for night outings and party wear.',
    material: 'Cotton Satin Blend',
    fit: 'Slim Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Spread Collar',
    fabric: 'Satin Stripe Weave',
    occasion: 'Party Wear, Casual Outings',
    stock: 20,
    isTrending: true,
    isNewArrival: true,
    isCasualWear: true
  },
  {
    id: 'prod_rust_striped_shirt',
    name: 'Rust Cotton Striped Shirt',
    category: 'Shirts',
    subCategory: 'Striped Shirts',
    price: 799,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Rust Striped', 'Amber'],
    ratings: 4.0,
    reviewCount: 29,
    description: 'Beautiful rust/terracotta-colored casual striped shirt with breathable cotton weave. Looks outstanding paired with blue or black denim.',
    material: '100% Organic Cotton',
    fit: 'Regular Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Classic Collar',
    fabric: 'Cotton Twill Stripe',
    occasion: 'Casual Daily Wear',
    stock: 18,
    isSummerCollection: true,
    isCasualWear: true
  },
  {
    id: 'prod_classic_white_linen',
    name: 'Classic White Linen Shirt',
    category: 'Shirts',
    subCategory: 'Linen Shirts',
    price: 1499,
    offerPrice: 999,
    images: ['https://images.unsplash.com/photo-1621072156002-e2fcc10d9714?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Pure White', 'Off-White'],
    ratings: 4.5,
    reviewCount: 56,
    description: 'Premium pure French linen shirt with high breathability. Styled with continuous button placket and curved hem. Perfect summer vacation staple.',
    material: '100% French Linen',
    fit: 'Relaxed Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Spread Collar',
    fabric: 'Pure Linen Weave',
    occasion: 'Resort Wear, Casual Friday',
    stock: 30,
    isTrending: true,
    isSummerCollection: true,
    isCasualWear: true
  },
  {
    id: 'prod_vintage_cuban_shirt',
    name: 'Vintage Cuban Collar Printed Shirt',
    category: 'Shirts',
    subCategory: 'Printed Shirts',
    price: 1199,
    offerPrice: 799,
    images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Cream Abstract', 'Warm Amber'],
    ratings: 4.4,
    reviewCount: 24,
    description: 'Fluid rayon drape and relaxed shoulders combined with a retro revere collar. Great for summer parties and streetwear styling.',
    material: 'Viscose Rayon',
    fit: 'Relaxed Street Fit',
    sleeve: 'Half Sleeve',
    neckline: 'Cuban Collar',
    fabric: 'Fluid Soft Rayon',
    occasion: 'Party, Beach Club',
    stock: 22,
    isBestSeller: true,
    isCasualWear: true
  },
  {
    id: 'prod_heritage_plaid_flannel',
    name: 'Heritage Madras Flannel Checked Shirt',
    category: 'Shirts',
    subCategory: 'Checked Shirts',
    price: 1299,
    offerPrice: 899,
    images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Navy/Crimson Plaid', 'Forest/Gold Plaid'],
    ratings: 4.6,
    reviewCount: 61,
    description: 'Double-brushed cotton flannel checked shirt. Outstanding heavy feel, warm and durable. Features dual chest pockets and adjustable cuffs.',
    material: '100% Organic Cotton Flannel',
    fit: 'Regular Trim',
    sleeve: 'Full Sleeve',
    neckline: 'Button Down',
    fabric: 'Heavy Brushed Cotton',
    occasion: 'Rugged Casual, Travel',
    stock: 19,
    isBestSeller: true,
    isCasualWear: true
  },
  {
    id: 'prod_emerald_satin_shirt',
    name: 'Emerald Green Satin Formal Shirt',
    category: 'Shirts',
    subCategory: 'Satin Shirts',
    price: 1199,
    offerPrice: 799,
    images: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Emerald Green', 'Pitch Black'],
    ratings: 4.3,
    reviewCount: 18,
    description: 'A luxurious solid satin shirt with a subtle sheen. Features French cuffs and spread collars for the ultimate evening attire.',
    material: 'Polyester Satin Silk',
    fit: 'Slim Premium Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Spread Collar',
    fabric: 'Fine Premium Satin Silk',
    occasion: 'Evening wear, Clubbing',
    stock: 15,
    isTrending: true,
    isFormalWear: true
  },
  {
    id: 'prod_chambray_denim_shirt',
    name: 'Rugged Chambray Denim Shirt',
    category: 'Shirts',
    subCategory: 'Denim Shirts',
    price: 999,
    offerPrice: 699,
    images: ['https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Indigo Wash', 'Light Chambray'],
    ratings: 4.5,
    reviewCount: 38,
    description: 'Lightweight denim chambray shirt with Western style twin snap-button chest pockets and classic point collar. Ideal for layering over plain white tees.',
    material: '100% Cotton Chambray',
    fit: 'Slim Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Point Collar',
    fabric: 'Chambray Cotton',
    occasion: 'Layered Casual, Rugged Outdoor',
    stock: 24,
    isNewArrival: true,
    isCasualWear: true
  },
  {
    id: 'prod_monochrome_checked_shirt',
    name: 'Monochrome Grid Checked Shirt',
    category: 'Shirts',
    subCategory: 'Checked Shirts',
    price: 799,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black & White Grid', 'Navy Grid'],
    ratings: 4.1,
    reviewCount: 20,
    description: 'Classic monochrome micro-checks in soft breathable cotton. Clean lines, lightweight, and incredibly versatile for everyday use.',
    material: '100% Combed Cotton',
    fit: 'Regular Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Classic Collar',
    fabric: 'Broadcloth Cotton Grid',
    occasion: 'Office Wear, Daily Casual',
    stock: 28,
    isCasualWear: true
  },
  {
    id: 'prod_black_satin_shirt',
    name: 'Jet Black Satin Party Shirt',
    category: 'Shirts',
    subCategory: 'Satin Shirts',
    price: 799,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Jet Black', 'Midnight Blue'],
    ratings: 4.2,
    reviewCount: 27,
    description: 'Deep glossy jet black cotton-satin blend shirt. Gives an incredibly sharp and elite silhouette under lights.',
    material: 'Satin Twill Blend',
    fit: 'Slim Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Spread Collar',
    fabric: 'High Density Satin Weave',
    occasion: 'Club Nights, Birthday Parties',
    stock: 16,
    isTrending: true,
    isCasualWear: true
  },
  {
    id: 'prod_pastel_linen_shirt',
    name: 'Pastel Sage Linen Casual Shirt',
    category: 'Shirts',
    subCategory: 'Linen Shirts',
    price: 799,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Sage Green', 'Pale Pink', 'Sky Blue'],
    ratings: 4.0,
    reviewCount: 14,
    description: 'Breezy and comfortable linen-viscose blend. Perfect pastel colors that stay bright. Offers all-day sweat-wicking comfort.',
    material: '50% Linen, 50% Viscose',
    fit: 'Relaxed Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Mandarin Collar',
    fabric: 'Linen Slub Blend',
    occasion: 'Brunch outings, Resort travel',
    stock: 21,
    isSummerCollection: true,
    isCasualWear: true
  },
  {
    id: 'prod_abstract_fluid_shirt',
    name: 'Abstract Paint Splash Floral Shirt',
    category: 'Shirts',
    subCategory: 'Printed Shirts',
    price: 799,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White Abstract Floral', 'Pink Retro Printed'],
    ratings: 4.1,
    reviewCount: 30,
    description: 'Expressive and colorful abstract print on premium fluid viscose. Light, airy, and very stylish for dynamic outfits.',
    material: '100% Viscose Rayon',
    fit: 'Oversized Fit',
    sleeve: 'Half Sleeve',
    neckline: 'Cuban Collar',
    fabric: 'Fluid Rayon Weave',
    occasion: 'Streetwear, Festival Gatherings',
    stock: 33,
    isNewArrival: true,
    isCasualWear: true
  },
  {
    id: 'prod_corduroy_overshirt',
    name: 'Vintage Corduroy Heavy Overshirt',
    category: 'Shirts',
    subCategory: 'Plain Shirts',
    price: 1399,
    offerPrice: 899,
    images: ['https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800&auto=format&fit=crop&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Tobacco Brown', 'Military Olive'],
    ratings: 4.4,
    reviewCount: 16,
    description: 'Thick, retro corduroy overshirt. Ideal for layering over plain t-shirts in chilly weather. Features durable heavy-gauge buttons.',
    material: '100% Cotton 12-Wale Corduroy',
    fit: 'Relaxed Boxy Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Spread Collar',
    fabric: 'Ribbed Corduroy',
    occasion: 'Layered Outwear, Casual Outings',
    stock: 12,
    isTrending: true,
    isCasualWear: true
  },
  {
    id: 'prod_royal_blue_satin',
    name: 'Royal Blue Premium Satin Shirt',
    category: 'Shirts',
    subCategory: 'Satin Shirts',
    price: 799,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Royal Blue', 'Champagne Gold'],
    ratings: 4.0,
    reviewCount: 19,
    description: 'Glow in luxury with our classic solid satin party shirt. The deep royal blue hue makes you stand out in any formal or celebration scene.',
    material: 'Satin Cotton Weave',
    fit: 'Slim Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Spread Collar',
    fabric: 'Rich Satin Twill',
    occasion: 'Festival Celebrations, Reception Parties',
    stock: 15,
    isFestivalCollection: true,
    isCasualWear: true
  },
  {
    id: 'prod_micro_stripe_linen',
    name: 'Micro-Stripe Breathable Linen Shirt',
    category: 'Shirts',
    subCategory: 'Striped Shirts',
    price: 799,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue/White Stripes', 'Pink/White Stripes'],
    ratings: 4.0,
    reviewCount: 22,
    description: 'Very clean, tiny micro-stripes on premium linen cotton blend. Unmatched cool feel during scorching summer heatwaves.',
    material: '40% Linen, 60% Cotton',
    fit: 'Regular Casual Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Classic Collar',
    fabric: 'Linen Micro Stripe',
    occasion: 'Weekend Lounge, Beach Resort',
    stock: 26,
    isSummerCollection: true,
    isCasualWear: true
  },

  // --- T-SHIRTS (10 Products) ---
  {
    id: 'prod_heavyweight_crewneck_tee',
    name: 'Heavyweight Premium Cotton Tee',
    category: 'T-Shirts',
    subCategory: 'Plain T-Shirts',
    price: 599,
    offerPrice: 399,
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Vintage Charcoal', 'Vanilla White', 'Sage Green'],
    ratings: 4.5,
    reviewCount: 88,
    description: 'Thick 240 GSM organic cotton knit. Stays highly structured and doesn\'t lose shape. Extremely comfortable relaxed shoulder fit.',
    material: '100% Ring-Spun Combed Cotton',
    fit: 'Relaxed Drop-Shoulder Fit',
    sleeve: 'Half Sleeve',
    neckline: 'Ribbed Crew Neck',
    fabric: 'Heavy Duty 240 GSM Knit',
    occasion: 'Streetwear, Casual Everyday Lounge',
    stock: 45,
    isBestSeller: true,
    isCasualWear: true
  },
  {
    id: 'prod_typography_graphic_tee',
    name: 'Retro Typography Heavy Graphic Tee',
    category: 'T-Shirts',
    subCategory: 'Graphic T-Shirts',
    price: 799,
    offerPrice: 549,
    images: ['https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Acid Wash Black', 'Off-White'],
    ratings: 4.4,
    reviewCount: 49,
    description: 'Features high-density puff print retro typography design. Perfect vintage aesthetic for everyday urban wear.',
    material: '100% Organic Cotton',
    fit: 'Oversized Loose Fit',
    sleeve: 'Half Sleeve',
    neckline: 'Thick Crew Collar',
    fabric: 'Medium Weight 210 GSM Cotton',
    occasion: 'Streetwear, Skateboarding',
    stock: 32,
    isTrending: true,
    isCasualWear: true
  },
  {
    id: 'prod_supima_vneck_tee',
    name: 'Premium Supima Silky V-Neck Tee',
    category: 'T-Shirts',
    subCategory: 'Plain T-Shirts',
    price: 799,
    offerPrice: 499,
    images: ['https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Heather Grey', 'Classic White', 'Matte Black'],
    ratings: 4.6,
    reviewCount: 37,
    description: 'Made from premium long-staple Supima cotton for an incredibly silky touch, exceptional color fastness, and high durability.',
    material: '100% Supima Cotton',
    fit: 'Tailored Fit',
    sleeve: 'Short Sleeve',
    neckline: 'Refined V-Neck',
    fabric: 'Interlock Supima Knit',
    occasion: 'Luxury Lounge, Undercoat Layering',
    stock: 35,
    isSummerCollection: true,
    isCasualWear: true
  },
  {
    id: 'prod_pima_polo',
    name: 'Minimalist Premium Pima Cotton Polo',
    category: 'T-Shirts',
    subCategory: 'Polo T-Shirts',
    price: 999,
    offerPrice: 699,
    images: ['https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=800&auto=format&fit=crop&q=80'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Classic Navy', 'Burgundy', 'Slate Grey'],
    ratings: 4.7,
    reviewCount: 52,
    description: 'Clean structured knit polo with 2-button placket and flat knit collar. Soft, smart, and perfect for working from home or smart casual office setups.',
    material: '100% Mercerized Pima Cotton',
    fit: 'Smart Athletic Fit',
    sleeve: 'Short Sleeve',
    neckline: 'Flat Knit Polo Collar',
    fabric: 'Pique Knit Cotton',
    occasion: 'Office Business Casual, Golf, Brunch',
    stock: 28,
    isBestSeller: true,
    isFormalWear: true
  },
  {
    id: 'prod_waffle_knit_tee',
    name: 'Textured Waffle Knit Long-Sleeve Tee',
    category: 'T-Shirts',
    subCategory: 'Plain T-Shirts',
    price: 999,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Oatmeal Beige', 'Dusty Olive'],
    ratings: 4.3,
    reviewCount: 21,
    description: 'Rich waffle-honeycomb texture that adds amazing depth to your outfit. Lightweight but provides comfortable warmth in breeze.',
    material: '60% Cotton, 40% Polyester Waffle Blend',
    fit: 'Regular Standard Fit',
    sleeve: 'Full Sleeve',
    neckline: 'Bound Crew Neck',
    fabric: 'Honeycomb Waffle Knit',
    occasion: 'Cozy Lounge, Casual Coffee Dates',
    stock: 20,
    isNewArrival: true,
    isCasualWear: true
  },
  {
    id: 'prod_nautical_stripe_tee',
    name: 'Nautical Striped Breton Tee',
    category: 'T-Shirts',
    subCategory: 'Plain T-Shirts',
    price: 699,
    offerPrice: 449,
    images: ['https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy/White Stripes', 'Red/White Stripes'],
    ratings: 4.2,
    reviewCount: 15,
    description: 'Timeless sailor striped tee in super soft combed cotton. Very clean and fresh Paris street-style look.',
    material: '100% Fine Combed Cotton',
    fit: 'Regular Standard Fit',
    sleeve: 'Short Sleeve',
    neckline: 'Crew Collar',
    fabric: 'Jersey Stripe Knit',
    occasion: 'Vacation Daily Wear, Summer Picnic',
    stock: 25,
    isSummerCollection: true,
    isCasualWear: true
  },
  {
    id: 'prod_pocket_slub_tee',
    name: 'Premium Slub Cotton Pocket Tee',
    category: 'T-Shirts',
    subCategory: 'Plain T-Shirts',
    price: 699,
    offerPrice: 449,
    images: ['https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Mustard Yellow', 'Mineral Blue'],
    ratings: 4.1,
    reviewCount: 19,
    description: 'Slub texture fabric with beautiful organic irregularities. Finished with a clean single chest pocket and detailed raw edges.',
    material: '100% Organic Slub Cotton',
    fit: 'Relaxed Fit',
    sleeve: 'Short Sleeve',
    neckline: 'Crew Neck',
    fabric: 'Slub Jersey Knit',
    occasion: 'Beachwear, Summer Travel',
    stock: 30,
    isSummerCollection: true,
    isCasualWear: true
  },
  {
    id: 'prod_vintage_band_tee',
    name: 'Vintage Rock & Roll Band Graphic Tee',
    category: 'T-Shirts',
    subCategory: 'Graphic T-Shirts',
    price: 799,
    offerPrice: 549,
    images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Aged Charcoal', 'Vintage White'],
    ratings: 4.6,
    reviewCount: 33,
    description: 'Thick wash-down heavy cotton graphic tee featuring retro faded graphic prints. Gives that genuine, heavily worn vintage rock aesthetic.',
    material: '100% Ring-Spun heavy cotton',
    fit: 'Oversized Fit',
    sleeve: 'Half Sleeve',
    neckline: 'Crew Neck',
    fabric: 'Stone Washed Heavy Cotton',
    occasion: 'Streetwear, Concert Nights, Lounge',
    stock: 18,
    isTrending: true,
    isCasualWear: true
  },
  {
    id: 'prod_performance_athletic_tee',
    name: 'Pro-Breathe Quick Dry Athletic Tee',
    category: 'T-Shirts',
    subCategory: 'Plain T-Shirts',
    price: 799,
    offerPrice: 499,
    images: ['https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Neon Lime', 'Active Teal', 'Slate Grey'],
    ratings: 4.4,
    reviewCount: 40,
    description: 'Engineered for extreme performance. High sweat-wicking properties, extreme mesh ventilation, and stretch panels for smooth athletic ranges.',
    material: '88% Polyester, 12% Spandex Mesh',
    fit: 'Compression / Smart Athletic Fit',
    sleeve: 'Short Sleeve',
    neckline: 'High Crew Neck',
    fabric: 'Double Knit Stretch Mesh',
    occasion: 'Gym Workouts, Marathons, Active Sports',
    stock: 35,
    isNewArrival: true,
    isCasualWear: true
  },
  {
    id: 'prod_striped_pocket_polo',
    name: 'Modern Breton Striped Pocket Polo',
    category: 'T-Shirts',
    subCategory: 'Polo T-Shirts',
    price: 899,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=800&auto=format&fit=crop&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Navy with White Stripe', 'Beige with Black Stripe'],
    ratings: 4.2,
    reviewCount: 11,
    description: 'Combining nautical stripes with polo structure. Features a single chest pocket and comfortable ribbed sleeves for a sharp bicep look.',
    material: '100% Pique Cotton',
    fit: 'Smart Fit',
    sleeve: 'Short Sleeve',
    neckline: 'Ribbed Polo Collar',
    fabric: 'Breton Pique Stripe',
    occasion: 'Brunch gatherings, Yacht club meetings',
    stock: 22,
    isCasualWear: true
  },

  // --- JEANS (8 Products) ---
  {
    id: 'prod_midnight_black_jeans',
    name: 'Midnight Black Comfort Stretch Jeans',
    category: 'Jeans',
    subCategory: 'Jeans',
    price: 1999,
    offerPrice: 1199,
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Stay-Black Matte'],
    ratings: 4.5,
    reviewCount: 92,
    description: 'Stay-black matte denim constructed with built-in premium 360-degree stretch. Never fades and retains incredible structure after multiple washes.',
    material: '92% Denim Cotton, 6% Poly, 2% Spandex',
    fit: 'Slim Tapered Fit',
    fabric: 'Stay-Black Stretch Denim',
    occasion: 'Nightout Wear, Smart Work Casual',
    stock: 40,
    isTrending: true,
    isBestSeller: true,
    isCasualWear: true
  },
  {
    id: 'prod_distressed_vintage_jeans',
    name: 'Vintage Wash Distressed Jeans',
    category: 'Jeans',
    subCategory: 'Jeans',
    price: 1899,
    offerPrice: 1099,
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Vintage Light Indigo'],
    ratings: 4.4,
    reviewCount: 31,
    description: 'Meticulously detailed hand-sanded whiskers and minor distressing on heavy vintage blue wash. Authentic lived-in denim design.',
    material: '100% Ring-Spun Denim Cotton',
    fit: 'Relaxed Tapered Fit',
    fabric: '13.5oz Heavy Duty Denim',
    occasion: 'Weekend Street Casual, Parties',
    stock: 18,
    isNewArrival: true,
    isCasualWear: true
  },
  {
    id: 'prod_raw_selvedge_jeans',
    name: 'Premium Japanese Raw Selvedge Jeans',
    category: 'Jeans',
    subCategory: 'Jeans',
    price: 2499,
    offerPrice: 1499,
    images: ['https://images.unsplash.com/photo-1582562124811-c09040d0a901?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Deep Indigo Raw'],
    ratings: 4.8,
    reviewCount: 15,
    description: 'For authentic denim purists. Features red-line ID selvedge on cuffs, stiff unwashed raw indigo denim that fades uniquely over your life.',
    material: '100% Japanese Selvedge Denim',
    fit: 'Regular Straight Fit',
    fabric: '14.5oz Rigid Raw Selvedge',
    occasion: 'Heritage Streetwear, Executive Casual',
    stock: 10,
    isTrending: true,
    isCasualWear: true
  },
  {
    id: 'prod_light_blue_relaxed_jeans',
    name: 'Classic 90s Light Blue Relaxed Jeans',
    category: 'Jeans',
    subCategory: 'Jeans',
    price: 1499,
    offerPrice: 899,
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['90s Bleached Indigo'],
    ratings: 4.2,
    reviewCount: 45,
    description: 'Straight out of the golden era of streetwear. Features wide loose leg openings, super comfortable high waist, and classic light stonewash.',
    material: '100% Organic Cotton Denim',
    fit: 'Relaxed Straight Fit',
    fabric: 'Mid-Weight 12oz Denim',
    occasion: 'Comfort Everyday Wear, Skateboarding',
    stock: 29,
    isSummerCollection: true,
    isCasualWear: true
  },
  {
    id: 'prod_charcoal_grey_jeans',
    name: 'Charcoal Grey Washed Slim Jeans',
    category: 'Jeans',
    subCategory: 'Jeans',
    price: 1599,
    offerPrice: 999,
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Washed Charcoal'],
    ratings: 4.3,
    reviewCount: 22,
    description: 'A beautiful alternative to blue and black. Gorgeous smoky grey fading with comfortable stretch properties.',
    material: '98% Cotton, 2% Elastane',
    fit: 'Slim Fit',
    fabric: 'Satin Denim Stretch',
    occasion: 'Evening Wear, Casual Dinner dates',
    stock: 23,
    isCasualWear: true
  },
  {
    id: 'prod_retro_acid_jeans',
    name: 'Retro Acid Wash Bleached Jeans',
    category: 'Jeans',
    subCategory: 'Jeans',
    price: 1799,
    offerPrice: 1099,
    images: ['https://images.unsplash.com/photo-1582562124811-c09040d0a901?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Acid Wash Blue'],
    ratings: 4.1,
    reviewCount: 12,
    description: 'Highly detailed high-contrast acid wash bleached pattern. Delivers a bold, retro rockstar look that gets noticed.',
    material: '100% Denim Cotton',
    fit: 'Slim Tapered Fit',
    fabric: 'Bleached Rigid Denim',
    occasion: 'Music Festivals, Concerts, Nightclubs',
    stock: 15,
    isFestivalCollection: true,
    isCasualWear: true
  },
  {
    id: 'prod_carpenter_utility_jeans',
    name: 'Carpenter Loose Utility Denim Pants',
    category: 'Jeans',
    subCategory: 'Jeans',
    price: 1999,
    offerPrice: 1199,
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Washed Indigo Blue'],
    ratings: 4.5,
    reviewCount: 19,
    description: 'Equipped with utility tool loops, side hammer holder, detailed triple stitch seams, and loose oversized streetwear cargo cut.',
    material: '100% Heavy duty Cotton Canvas',
    fit: 'Loose Carpenter Fit',
    fabric: '14oz Cotton Duck Denim',
    occasion: 'Streetwear, Skate Park, Outdoors',
    stock: 16,
    isNewArrival: true,
    isCasualWear: true
  },
  {
    id: 'prod_stay_white_jeans',
    name: 'Stay-Clean Crisp White Jeans',
    category: 'Jeans',
    subCategory: 'Jeans',
    price: 1799,
    offerPrice: 1099,
    images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Stay White'],
    ratings: 4.0,
    reviewCount: 8,
    description: 'Features specialized liquid and dirt repellent nano-coating. Elegant slim fit looking phenomenal under bright sun.',
    material: '97% Cotton, 3% Elastane',
    fit: 'Slim Fit',
    fabric: 'Hydrophobic Nanotech Denim',
    occasion: 'Resort Beach Wear, Elite Summer Events',
    stock: 12,
    isSummerCollection: true,
    isCasualWear: true
  },

  // --- PANTS & TROUSERS (10 Products) ---
  {
    id: 'prod_khaki_chino_trousers',
    name: 'Classic Khaki Smart Chino Trousers',
    category: 'Pants',
    subCategory: 'Chinos',
    price: 1499,
    offerPrice: 899,
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Khaki Beige', 'Classic Navy'],
    ratings: 4.6,
    reviewCount: 74,
    description: 'Flat front dress chinos in mercerized cotton stretch twill. Stays completely crisp, offering unbelievable ease from office to bar.',
    material: '98% Mercerized Cotton, 2% Elastane',
    fit: 'Slim Straight Fit',
    fabric: 'Stretch Cotton Twill',
    occasion: 'Business Casual Office, Dinners, Golf',
    stock: 35,
    isBestSeller: true,
    isFormalWear: true
  },
  {
    id: 'prod_slate_grey_trousers',
    name: 'Pleated Slate Grey Trousers',
    category: 'Trousers',
    subCategory: 'Trousers',
    price: 1599,
    offerPrice: 999,
    images: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Slate Grey', 'Classic Black'],
    ratings: 4.5,
    reviewCount: 31,
    description: 'Single pleat classic dress trousers. Perfect smart formal drape that pairs exceptionally with crisp tucked-in shirts.',
    material: '80% Poly, 20% Fine Wool Blend',
    fit: 'Modern Slim Tapered',
    fabric: 'Smooth Worsted Drapery',
    occasion: 'Boardrooms, Formal Dinners',
    stock: 22,
    isTrending: true,
    isFormalWear: true
  },
  {
    id: 'prod_cargo_utility_pants',
    name: 'Cargo Utility Multi-Pocket Pants',
    category: 'Pants',
    subCategory: 'Cargo Pants',
    price: 1499,
    offerPrice: 899,
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Olive Drab', 'Desert Tan'],
    ratings: 4.4,
    reviewCount: 41,
    description: 'Rugged cargo pants with high utility storage. Designed with knee articulation points and durable reinforced seams for high-intensity active lifestyle.',
    material: '100% Heavy Duty Cotton Ripstop',
    fit: 'Relaxed Tapered',
    fabric: 'Ripstop Grid Weave',
    occasion: 'Hiking, Travel, Streetwear',
    stock: 28,
    isTrending: true,
    isCasualWear: true
  },
  {
    id: 'prod_sand_linen_pants',
    name: 'Breezy Drawstring Sand Linen Pants',
    category: 'Pants',
    subCategory: 'Linen Pants',
    price: 1599,
    offerPrice: 999,
    images: ['https://images.unsplash.com/photo-1517462964-21fdcec3f25b?w=800&auto=format&fit=crop&q=80'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Natural Sand', 'Breezy Navy'],
    ratings: 4.2,
    reviewCount: 16,
    description: 'Vacation relaxation pants. Comes with comfortable elastic waistband and adjustable drawcords, deep side pockets.',
    material: '55% Linen, 45% Organic Cotton',
    fit: 'Relaxed Tapered Fit',
    fabric: 'Slubby Linen Cotton Weave',
    occasion: 'Beach holiday, Summer evening strolls',
    stock: 18,
    isSummerCollection: true,
    isCasualWear: true
  },
  {
    id: 'prod_pleated_charcoal_trousers',
    name: 'Premium Wool Blend Formal Trousers',
    category: 'Trousers',
    subCategory: 'Trousers',
    price: 1999,
    offerPrice: 1299,
    images: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Charcoal Grey', 'Deep Navy'],
    ratings: 4.7,
    reviewCount: 23,
    description: 'Elegantly tailored with double pleats. Provides premium comfortable groin space while tapering beautifully down the ankle.',
    material: '70% Wool, 30% Polyester Blend',
    fit: 'Tapered Ankle Fit',
    fabric: 'Rich Worsted Wool',
    occasion: 'Weddings, Formal Gala, Presentations',
    stock: 15,
    isNewArrival: true,
    isFormalWear: true
  },
  {
    id: 'prod_glen_plaid_pants',
    name: 'Tailored Glen Plaid Smart Pants',
    category: 'Pants',
    subCategory: 'Chinos',
    price: 1599,
    offerPrice: 999,
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Grey Prince-of-Wales Check'],
    ratings: 4.4,
    reviewCount: 14,
    description: 'Subtle high-contrast glen plaid check styling in incredibly smooth knit stretch. Delivers instant European style.',
    material: '65% Rayon, 30% Nylon, 5% Spandex',
    fit: 'Slim Tapered Fit',
    fabric: 'Jacquard Ponte Knit Check',
    occasion: 'Art exhibitions, Upscale Dinners, Lounge',
    stock: 19,
    isTrending: true,
    isCasualWear: true
  },
  {
    id: 'prod_comfort_navy_trousers',
    name: 'Comfort Stretch Navy Trousers',
    category: 'Trousers',
    subCategory: 'Trousers',
    price: 1499,
    offerPrice: 899,
    images: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Classic Navy', 'Stone Beige'],
    ratings: 4.3,
    reviewCount: 30,
    description: 'Engineered with hidden elastic side expansion tab. Perfect for long office seating sessions or flights.',
    material: '90% Cotton, 10% Lycra',
    fit: 'Regular Straight Fit',
    fabric: 'Flexible Micro Twill',
    occasion: 'Office Daily Wear, Flight Travel',
    stock: 32,
    isBestSeller: true,
    isFormalWear: true
  },
  {
    id: 'prod_athletic_knit_joggers',
    name: 'Athletic Slim Knit Jogger Pants',
    category: 'Pants',
    subCategory: 'Cargo Pants',
    price: 999,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1517462964-21fdcec3f25b?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Melange Grey', 'Carbon Black'],
    ratings: 4.5,
    reviewCount: 62,
    description: 'Ultra-soft French terry joggers with zipper pockets and heavy premium drawstring toggles. Ideal fitness and lounging essential.',
    material: '80% Combed Cotton, 20% Polyester Terry',
    fit: 'Slim Jogger Cuffed Fit',
    fabric: 'Double Face French Terry',
    occasion: 'Morning Jogs, High-Speed Airport Travel',
    stock: 40,
    isSummerCollection: true,
    isCasualWear: true
  },
  {
    id: 'prod_relaxed_corduroy_pants',
    name: 'Relaxed Fit Corduroy Trousers',
    category: 'Pants',
    subCategory: 'Chinos',
    price: 1699,
    offerPrice: 1099,
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Chocolate Brown', 'Dark Forest Green'],
    ratings: 4.2,
    reviewCount: 11,
    description: 'Thick, lush 8-wale corduroy trousers with an easy straight leg drop. Delivers premium vintage structure and incredible winter warmth.',
    material: '100% Combed Corduroy Cotton',
    fit: 'Relaxed Straight Leg Fit',
    fabric: 'Heavy Gauge Corduroy',
    occasion: 'Cozy Winter Strolls, Vintage Aesthetic Wear',
    stock: 14,
    isNewArrival: true,
    isCasualWear: true
  },
  {
    id: 'prod_sage_green_chinos',
    name: 'Sage Green Comfort Chinos',
    category: 'Pants',
    subCategory: 'Chinos',
    price: 1499,
    offerPrice: 899,
    images: ['https://images.unsplash.com/photo-1517462964-21fdcec3f25b?w=800&auto=format&fit=crop&q=80'],
    sizes: ['30', '32', '34', '36'],
    colors: ['Sage Green', 'Warm Olive'],
    ratings: 4.5,
    reviewCount: 28,
    description: 'Incredibly unique pastel sage green shade. Mercerized wash gives a very soft touch and outstanding breathability.',
    material: '98% Cotton Sateen, 2% Elastane',
    fit: 'Slim Fit',
    fabric: 'Luxe Stretch Sateen Twill',
    occasion: 'Spring outings, Daytime brunches, Dating',
    stock: 26,
    isSummerCollection: true,
    isCasualWear: true
  },

  // --- JACKETS (5 Products) ---
  {
    id: 'prod_suede_bomber_jacket',
    name: 'Suede Bomber Minimalist Jacket',
    category: 'Jackets',
    subCategory: 'Jackets',
    price: 2999,
    offerPrice: 1999,
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Vintage Tan', 'Tobacco Suede'],
    ratings: 4.9,
    reviewCount: 45,
    description: 'Hand-picked supple faux-suede leather with premium micro-rib knit borders. Designed with gunmetal heavy zippers and smooth inner satin lining.',
    material: 'Supple Faux Suede Leather, Satin Inner Lining',
    fit: 'Sleek Bomber Fit',
    fabric: 'Premium Ultra-Soft Faux Suede',
    occasion: 'Riding, Premium Club Evenings',
    stock: 12,
    isTrending: true,
    isBestSeller: true
  },
  {
    id: 'prod_classic_denim_jacket',
    name: 'Classic Indigo Denim Trucker Jacket',
    category: 'Jackets',
    subCategory: 'Jackets',
    price: 2499,
    offerPrice: 1499,
    images: ['https://images.unsplash.com/photo-1495105787522-5334e3ffa0ef?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Authentic Indigo', 'Stone Washed Black'],
    ratings: 4.7,
    reviewCount: 55,
    description: 'A masterpiece in classic workwear. Built with heavy-duty rigid ring-spun denim cotton, signature metallic shank buttons and adjustable waist tabs.',
    material: '100% Rigid Heavy Cotton Denim',
    fit: 'Classic Trim Trucker',
    fabric: '13.5oz Raw Denim Weave',
    occasion: 'Layered Outerwear, Casual Streetwear',
    stock: 20,
    isBestSeller: true,
    isCasualWear: true
  },
  {
    id: 'prod_tech_waterproof_windbreaker',
    name: 'Tech Shell Waterproof Windbreaker',
    category: 'Jackets',
    subCategory: 'Jackets',
    price: 1999,
    offerPrice: 1299,
    images: ['https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&auto=format&fit=crop&q=80'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Matte Black', 'Digital Cyan'],
    ratings: 4.5,
    reviewCount: 18,
    description: 'Fully sealed seams, custom YKK water-repellent zippers, micro-mesh lining for extreme breathability. Shields completely from rain and winds.',
    material: '100% Ripstop Nylon with DWR Coating',
    fit: 'Regular Active Fit',
    fabric: 'Durable Water Resistant Shell',
    occasion: 'Monsoon Treks, Travel, Active Running',
    stock: 15,
    isNewArrival: true,
    isCasualWear: true
  },
  {
    id: 'prod_sherpa_cord_jacket',
    name: 'Sherpa-Lined Corduroy Trucker Jacket',
    category: 'Jackets',
    subCategory: 'Jackets',
    price: 2799,
    offerPrice: 1799,
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Tan Sherpa', 'Onyx Sherpa'],
    ratings: 4.8,
    reviewCount: 22,
    description: 'Thick vintage wide-rib corduroy outerwear fully insulated with rich, soft sherpa fleece. Keeps you incredibly cozy during severe winter nights.',
    material: '100% Cotton Corduroy, Sherpa Fleece Lining',
    fit: 'Comfort Boxy Trucker',
    fabric: 'Heavy Duty Corduroy & Fleece',
    occasion: 'Winter Holiday Travel, Night Camping',
    stock: 10,
    isTrending: true
  },
  {
    id: 'prod_unstructured_blazer',
    name: 'Casual Unstructured Summer Blazer',
    category: 'Jackets',
    subCategory: 'Jackets',
    price: 2499,
    offerPrice: 1499,
    images: ['https://images.unsplash.com/photo-1495105787522-5334e3ffa0ef?w=800&auto=format&fit=crop&q=80'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Desert Sand', 'Steel Grey'],
    ratings: 4.4,
    reviewCount: 16,
    description: 'A blazer with zero stiff shoulder padding. Drapes smoothly like a shirt. Perfect smart-casual savior for warm climate business meets.',
    material: '70% Cotton, 30% Linen Blend',
    fit: 'Relaxed Tailored Fit',
    fabric: 'Linen Slub Drapery',
    occasion: 'Art Events, Beach Weddings, Formal Dinners',
    stock: 14,
    isNewArrival: true,
    isSummerCollection: true,
    isFormalWear: true
  },

  // --- ACCESSORIES (5 Products) ---
  {
    id: 'prod_leather_heritage_watch',
    name: 'Heritage Chronograph Leather Watch',
    category: 'Accessories',
    subCategory: 'Accessories',
    price: 2999,
    offerPrice: 1899,
    images: ['https://images.unsplash.com/photo-1524222247344-550fb8ecf7db?w=800&auto=format&fit=crop&q=80'],
    sizes: ['One Size'],
    colors: ['Rose Gold / Tan Suede'],
    ratings: 4.8,
    reviewCount: 63,
    description: 'Breathtaking chronograph wristwatch with premium Miyota Japanese quartz movement. Features custom rose gold framing and supple Italian suede leather straps.',
    material: '316L Stainless Steel, Full Grain Suede Leather',
    fit: 'One Size / Adjustable Fit',
    fabric: 'Fine Gauge Genuine Italian Leather',
    occasion: 'Premium Formal, Business Casual',
    stock: 15,
    isTrending: true,
    isBestSeller: true
  },
  {
    id: 'prod_weekend_canvas_duffel',
    name: 'Utility Canvas Weekend Duffel Bag',
    category: 'Accessories',
    subCategory: 'Accessories',
    price: 1999,
    offerPrice: 1199,
    images: ['https://images.unsplash.com/photo-1624222247344-550fb8ecf7db?w=800&auto=format&fit=crop&q=80'],
    sizes: ['One Size'],
    colors: ['Military Khaki', 'Slate Grey'],
    ratings: 4.6,
    reviewCount: 39,
    description: 'Extremely spacious 42 Liter travel bag constructed with heavy water-resistant duck canvas. Trimmed with premium buffalo pull-up leather.',
    material: '18oz Heavy Duty Cotton Canvas & Buffalo Leather',
    fit: '42 Liters Capacity',
    fabric: 'Water Resistant Duck Canvas',
    occasion: 'Travel, Weekend Duffel, Active Gym',
    stock: 25,
    isNewArrival: true
  },
  {
    id: 'prod_polarized_sunglasses',
    name: 'Matte Black Polarized Sunglasses',
    category: 'Accessories',
    subCategory: 'Accessories',
    price: 999,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80'],
    sizes: ['One Size'],
    colors: ['Matte Black with Dark Lens'],
    ratings: 4.5,
    reviewCount: 29,
    description: 'Equipped with heavy-duty zero-flicker polarized filters. Lightweight polycarbonate framing with scratch-resistant premium UV400 lenses.',
    material: 'High-Impact Polycarbonate, UV400 Polarized Lenses',
    fit: 'Medium Standard Fit',
    fabric: 'Matte Finish Resin Frame',
    occasion: 'Driving, Sea Travel, Sunny Days Out',
    stock: 35,
    isSummerCollection: true,
    isTrending: true
  },
  {
    id: 'prod_handcrafted_leather_belt',
    name: 'Handcrafted Full-Grain Leather Belt',
    category: 'Accessories',
    subCategory: 'Accessories',
    price: 999,
    offerPrice: 599,
    images: ['https://images.unsplash.com/photo-1524222247344-550fb8ecf7db?w=800&auto=format&fit=crop&q=80'],
    sizes: ['32', '34', '36', '38'],
    colors: ['Cognac Brown', 'Dark Espresso'],
    ratings: 4.7,
    reviewCount: 42,
    description: 'Single-strip solid premium cowhide leather. Antique polished brass buckle closures with hand-burnished raw edges. Built to last a lifetime.',
    material: '100% Solid Cowhide Full-Grain Leather, Solid Brass',
    fit: 'Width 1.5 inches',
    fabric: 'Hand-Finished Veg-Tanned Leather',
    occasion: 'Daily Work Wear, Jeans Casual Outings',
    stock: 30,
    isBestSeller: true
  },
  {
    id: 'prod_minimalist_suede_wallet',
    name: 'Minimalist Slim Suede RFID Wallet',
    category: 'Accessories',
    subCategory: 'Accessories',
    price: 799,
    offerPrice: 499,
    images: ['https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80'],
    sizes: ['One Size'],
    colors: ['Tan Suede', 'Forest Green Suede'],
    ratings: 4.4,
    reviewCount: 17,
    description: 'Advanced RFID-shielding slim pocket profile. Holds up to 6 cards and folded cash seamlessly in elegant premium suede leather styling.',
    material: 'Genuine Italian Suede, Metallic RFID Guard Mesh',
    fit: 'Super Slim pocket Cardholder',
    fabric: 'Supple Suede Leather Finish',
    occasion: 'Daily Active Travel, Minimalist Utility',
    stock: 45,
    isNewArrival: true
  }
];

// Helper to recursively remove undefined properties for Firestore compatibility
function cleanUndefined<T>(obj: T): T {
  if (obj === null || typeof obj !== 'object') {
    return obj;
  }
  const result: any = Array.isArray(obj) ? [] : {};
  for (const key in obj) {
    if (Object.prototype.hasOwnProperty.call(obj, key)) {
      const val = (obj as any)[key];
      if (val !== undefined) {
        result[key] = cleanUndefined(val);
      }
    }
  }
  return result;
}

// Helper to convert compact RAW representation to fully typed Product models
export const INITIAL_PRODUCTS: Product[] = RAW_PRODUCTS_DATA.map((p) => cleanUndefined({
  id: p.id,
  name: p.name,
  brand: 'Rightnow Garments',
  category: p.category,
  subCategory: p.subCategory,
  price: p.price,
  offerPrice: p.offerPrice,
  images: p.images,
  sizes: p.sizes,
  colors: p.colors,
  ratings: p.ratings,
  reviewCount: p.reviewCount,
  description: p.description,
  specifications: {
    material: p.material,
    fit: p.fit,
    sleeve: p.sleeve,
    neckline: p.neckline,
    fabric: p.fabric,
    occasion: p.occasion
  },
  stock: p.stock,
  isTrending: p.isTrending,
  isBestSeller: p.isBestSeller,
  isNewArrival: p.isNewArrival,
  isTodayDeal: p.isTodayDeal,
  isSummerCollection: p.isSummerCollection,
  isFormalWear: p.isFormalWear,
  isCasualWear: p.isCasualWear,
  isFestivalCollection: p.isFestivalCollection
}));

export const INITIAL_COUPONS: Coupon[] = [
  {
    code: 'FIRST10',
    discountType: 'percentage',
    value: 10,
    minPurchase: 1000,
    isActive: true,
    description: 'Get 10% OFF on your very first order over ₹1,000!'
  },
  {
    code: 'RIGHTNOW200',
    discountType: 'fixed',
    value: 200,
    minPurchase: 1500,
    isActive: true,
    description: 'Get flat ₹200 OFF on order totals above ₹1,500!'
  },
  {
    code: 'FESTIVAL300',
    discountType: 'fixed',
    value: 300,
    minPurchase: 2000,
    isActive: true,
    description: 'Special flat ₹300 OFF for purchases above ₹2,000!'
  }
];

export async function seedDatabase() {
  try {
    const productsRef = collection(db, 'products');
    const productsSnapshot = await getDocs(productsRef);
    
    // Clean up obsolete products that are not part of our new 50+ list
    const activeIds = new Set(INITIAL_PRODUCTS.map(p => p.id));
    const extraProducts = productsSnapshot.docs.filter(doc => !activeIds.has(doc.id));
    if (extraProducts.length > 0) {
      console.log(`Removing ${extraProducts.length} obsolete products...`);
      const cleanupBatch = writeBatch(db);
      extraProducts.forEach(doc => {
        cleanupBatch.delete(doc.ref);
      });
      await cleanupBatch.commit();
    }

    const existingIds = new Set<string>();
    productsSnapshot.forEach(doc => {
      if (activeIds.has(doc.id)) {
        existingIds.add(doc.id);
      }
    });

    const missingProducts = INITIAL_PRODUCTS.filter(p => !existingIds.has(p.id));

    if (missingProducts.length > 0) {
      console.log(`Seeding ${missingProducts.length} missing products...`);
      // Since Firestore batch limit is 500 now, but chunking in batches of 40 is extremely safe and prevents timeouts.
      const BATCH_SIZE = 40;
      for (let i = 0; i < missingProducts.length; i += BATCH_SIZE) {
        const batch = writeBatch(db);
        const chunk = missingProducts.slice(i, i + BATCH_SIZE);
        chunk.forEach((product) => {
          const docRef = doc(productsRef, product.id);
          batch.set(docRef, product);
        });
        await batch.commit();
        console.log(`Committed chunk ${i / BATCH_SIZE + 1} of ${Math.ceil(missingProducts.length / BATCH_SIZE)}`);
      }
      console.log('Successfully seeded missing products!');
    } else {
      console.log('All initial products already seeded!');
    }

    const couponsRef = collection(db, 'coupons');
    const couponsSnapshot = await getDocs(couponsRef);
    
    const existingCoupons = new Set<string>();
    couponsSnapshot.forEach(doc => {
      existingCoupons.add(doc.id);
    });

    const missingCoupons = INITIAL_COUPONS.filter(c => !existingCoupons.has(c.code));

    if (missingCoupons.length > 0) {
      console.log(`Seeding ${missingCoupons.length} missing coupons...`);
      const batch = writeBatch(db);
      missingCoupons.forEach((coupon) => {
        const docRef = doc(couponsRef, coupon.code);
        batch.set(docRef, coupon);
      });
      await batch.commit();
      console.log('Successfully seeded missing coupons!');
    } else {
      console.log('All initial coupons already seeded!');
    }
  } catch (error) {
    console.error('Error seeding database:', error);
  }
}
